# safe: false
# auto: true
# server: true
pygments: true

# now the default permalink
# permalink: /:year/:month/:day/:title

# category_dir: topics
# category_title_prefix: All about&nbsp;

# Number of posts per page
paginate: 5
paginate_path: "blog/page:num"

permalink: /blog/:year/:month/:day/:title.html